#!/bin/bash

# Author: Victoria Brunner
# Date Written: March 5, 2023
# Date Modified: March 5, 2023

# Description:
# Automatically create a copy of contents from a local bare Git repo into a new project folder.
# Must be in same directory where the bare repo of your choice is.

# Usage:
# On one terminal, first run: git daemon --verbose --export-all --base_path=.
# Then, on another terminal, run: bareclone <new_folder_name_or_path> <existing_bare_repo_name>
# NOTE: BOTH TERMINALS MUST BE IN DIRECTORY WHERE THE BARE REPO OF YOUR CHOICE IS BEFORE RUNNING BOTH COMMANDS!

git clone git://localhost/$2.git $1
cd $1

default_editor="$(git config --global core.editor)"

case "$default_editor" in
    "code --wait" | "code -w") code .;;
    "nova --wait" | "nova -w") nova .;;
    *) echo "Clone created. Open or create a file for your directory in your text editor.";;
esac
