#!/bin/bash

# Author: Victoria Brunner
# Date Written: March 5, 2023
# Date Modified: March 5, 2023

# Description:
# Automatically create a cloned bare repository from any local Git repo.
# Note: You must be in the project folder where the repo you want to clone is.

# Usage:
# mkbare <existing_folder_name>

cd ..
git clone --bare $1 $1.git
cd $1.git

default_editor="$(git config --global core.editor)"

remote_repo_name=$(python3 remote_repo_parse.py $2)

case "$default_editor" in
    "code --wait" | "code -w") code .;;
    "nova --wait" | "nova -w") nova .;;
    *) echo "Clone created. Open or create a file for your directory in your text editor.";;
esac
