#!/opt/homebrew/bin/bash

# or #!/bin/bash

# Author: Victoria Brunner
# Date Written: March 8, 2023
# Date Modified: November 11, 2023

# Description:
# Open an existing repo at some specified branch.  Create new branch and open there if branch does not exist yet.

# Usage:
# openrepo <project_folder_path_or_name> <branch>

cd $1;

default_editor="$(git config --global core.editor)"
current_branch="$(git rev-parse --abbrev-ref HEAD)"  #get name of current branch
git checkout $branch


case "$default_editor" in
    "code --wait" | "code -w") code .;;
    "nova --wait" | "nova -w") nova .;;
    *) echo "Switched to branch $2.  Use ls to check contents of repo, touch to make a new file, or mkdir to create a new folder in this branch.";;
esac

